// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/6/2025, 12:48:59 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/Rudolf/Work/poseidonnew/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/plugins/**/*.{js,ts,mjs}","/Users/Rudolf/Work/poseidonnew/composables/**/*.{js,ts,mjs}","/Users/Rudolf/Work/poseidonnew/utils/**/*.{js,ts,mjs}","/Users/Rudolf/Work/poseidonnew/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/poseidonnew/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;