// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/2/2026, 9:07:07 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/Rudolf/Work/mai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/plugins/**/*.{js,ts,mjs}","/Users/Rudolf/Work/mai/composables/**/*.{js,ts,mjs}","/Users/Rudolf/Work/mai/utils/**/*.{js,ts,mjs}","/Users/Rudolf/Work/mai/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/Rudolf/Work/mai/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;