
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Aboutus': typeof import("../components/Aboutus.vue")['default']
    'BicycleHero': typeof import("../components/BicycleHero.vue")['default']
    'BicycleRoutes': typeof import("../components/BicycleRoutes.vue")['default']
    'CTA': typeof import("../components/CTA.vue")['default']
    'EventsHero': typeof import("../components/EventsHero.vue")['default']
    'EventsRoutes': typeof import("../components/EventsRoutes.vue")['default']
    'ExcursionsHero': typeof import("../components/ExcursionsHero.vue")['default']
    'ExcursionsRoutes': typeof import("../components/ExcursionsRoutes.vue")['default']
    'Faq': typeof import("../components/Faq.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'Hero': typeof import("../components/Hero.vue")['default']
    'Map': typeof import("../components/Map.vue")['default']
    'RentABoatHero': typeof import("../components/RentABoatHero.vue")['default']
    'Services': typeof import("../components/Services.vue")['default']
    'TaxiBoatHero': typeof import("../components/TaxiBoatHero.vue")['default']
    'Testimonial': typeof import("../components/Testimonial.vue")['default']
    'TransferRoutes': typeof import("../components/TransferRoutes.vue")['default']
    'TransfersHero': typeof import("../components/TransfersHero.vue")['default']
    'VehicleFleet': typeof import("../components/VehicleFleet.vue")['default']
    'Widget': typeof import("../components/Widget.vue")['default']
    'Popup': typeof import("../components/popup.vue")['default']
    'NuxtMarquee': typeof import("../node_modules/nuxt-marquee/dist/runtime/components/NuxtMarquee.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutus': typeof import("../components/Aboutus.vue")['default']
    'LazyBicycleHero': typeof import("../components/BicycleHero.vue")['default']
    'LazyBicycleRoutes': typeof import("../components/BicycleRoutes.vue")['default']
    'LazyCTA': typeof import("../components/CTA.vue")['default']
    'LazyEventsHero': typeof import("../components/EventsHero.vue")['default']
    'LazyEventsRoutes': typeof import("../components/EventsRoutes.vue")['default']
    'LazyExcursionsHero': typeof import("../components/ExcursionsHero.vue")['default']
    'LazyExcursionsRoutes': typeof import("../components/ExcursionsRoutes.vue")['default']
    'LazyFaq': typeof import("../components/Faq.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyHero': typeof import("../components/Hero.vue")['default']
    'LazyMap': typeof import("../components/Map.vue")['default']
    'LazyRentABoatHero': typeof import("../components/RentABoatHero.vue")['default']
    'LazyServices': typeof import("../components/Services.vue")['default']
    'LazyTaxiBoatHero': typeof import("../components/TaxiBoatHero.vue")['default']
    'LazyTestimonial': typeof import("../components/Testimonial.vue")['default']
    'LazyTransferRoutes': typeof import("../components/TransferRoutes.vue")['default']
    'LazyTransfersHero': typeof import("../components/TransfersHero.vue")['default']
    'LazyVehicleFleet': typeof import("../components/VehicleFleet.vue")['default']
    'LazyWidget': typeof import("../components/Widget.vue")['default']
    'LazyPopup': typeof import("../components/popup.vue")['default']
    'LazyNuxtMarquee': typeof import("../node_modules/nuxt-marquee/dist/runtime/components/NuxtMarquee.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Aboutus: typeof import("../components/Aboutus.vue")['default']
export const BicycleHero: typeof import("../components/BicycleHero.vue")['default']
export const BicycleRoutes: typeof import("../components/BicycleRoutes.vue")['default']
export const CTA: typeof import("../components/CTA.vue")['default']
export const EventsHero: typeof import("../components/EventsHero.vue")['default']
export const EventsRoutes: typeof import("../components/EventsRoutes.vue")['default']
export const ExcursionsHero: typeof import("../components/ExcursionsHero.vue")['default']
export const ExcursionsRoutes: typeof import("../components/ExcursionsRoutes.vue")['default']
export const Faq: typeof import("../components/Faq.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Hero: typeof import("../components/Hero.vue")['default']
export const Map: typeof import("../components/Map.vue")['default']
export const RentABoatHero: typeof import("../components/RentABoatHero.vue")['default']
export const Services: typeof import("../components/Services.vue")['default']
export const TaxiBoatHero: typeof import("../components/TaxiBoatHero.vue")['default']
export const Testimonial: typeof import("../components/Testimonial.vue")['default']
export const TransferRoutes: typeof import("../components/TransferRoutes.vue")['default']
export const TransfersHero: typeof import("../components/TransfersHero.vue")['default']
export const VehicleFleet: typeof import("../components/VehicleFleet.vue")['default']
export const Widget: typeof import("../components/Widget.vue")['default']
export const Popup: typeof import("../components/popup.vue")['default']
export const NuxtMarquee: typeof import("../node_modules/nuxt-marquee/dist/runtime/components/NuxtMarquee.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutus: typeof import("../components/Aboutus.vue")['default']
export const LazyBicycleHero: typeof import("../components/BicycleHero.vue")['default']
export const LazyBicycleRoutes: typeof import("../components/BicycleRoutes.vue")['default']
export const LazyCTA: typeof import("../components/CTA.vue")['default']
export const LazyEventsHero: typeof import("../components/EventsHero.vue")['default']
export const LazyEventsRoutes: typeof import("../components/EventsRoutes.vue")['default']
export const LazyExcursionsHero: typeof import("../components/ExcursionsHero.vue")['default']
export const LazyExcursionsRoutes: typeof import("../components/ExcursionsRoutes.vue")['default']
export const LazyFaq: typeof import("../components/Faq.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyHero: typeof import("../components/Hero.vue")['default']
export const LazyMap: typeof import("../components/Map.vue")['default']
export const LazyRentABoatHero: typeof import("../components/RentABoatHero.vue")['default']
export const LazyServices: typeof import("../components/Services.vue")['default']
export const LazyTaxiBoatHero: typeof import("../components/TaxiBoatHero.vue")['default']
export const LazyTestimonial: typeof import("../components/Testimonial.vue")['default']
export const LazyTransferRoutes: typeof import("../components/TransferRoutes.vue")['default']
export const LazyTransfersHero: typeof import("../components/TransfersHero.vue")['default']
export const LazyVehicleFleet: typeof import("../components/VehicleFleet.vue")['default']
export const LazyWidget: typeof import("../components/Widget.vue")['default']
export const LazyPopup: typeof import("../components/popup.vue")['default']
export const LazyNuxtMarquee: typeof import("../node_modules/nuxt-marquee/dist/runtime/components/NuxtMarquee.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
